### ISSUE TITLE
NV-12 support

### ISSUE THREAD

**Issue by austinbhale** [StereoKit/sk_gpu#21]
For this header library, can we just add another `skg_tex_fmt_` for `DXGI_FORMAT_NV12` (and all relevant calls), or do there need to be further additions here? Likewise for adding NV-12 as a `TexFormat` in StereoKit.

I'll be testing it out today with something like [this shader](https://github.com/microsoft/Windows-universal-samples/blob/main/Samples/HolographicFaceTracking/cpp/Content/Shaders/QuadPixelShaderNV12.hlsl) today and can report back here

**Comment by maluoi** [comment]
I don't have much experience with this category of interlaced texture formats, so I don't really know what sort of pitfalls to expect! It's likely there are some, it kinda sounds like there [may need to be multiple shader resource views per-texture](https://learn.microsoft.com/en-us/windows/win32/api/dxgiformat/ne-dxgiformat-dxgi_format) or something? Which doesn't look like it would fit well into SK's abstraction of what a texture is.

This work would also need to be done for OpenGL as well to make the format portable.

**Comment by austinbhale** [comment]
Yes exactly, there'd be one each for the [luminance and chrominance channels](https://github.com/microsoft/Windows-universal-samples/blob/ad9a0c4def222aaf044e51f8ee0939911cb58471/Samples/HolographicFaceTracking/cpp/Content/NV12VideoTexture.cpp#L97). That'd be some conditional refactoring that we can probably avoid for a somewhat niche case like this. Though NV-12 is supported for hardware decoding video. I think I can just use the d3d context from here for a custom solution.

I can write an overload for a `Tex` to set this data but would still like to make use of a `Sprite`, so I'll push a PR for creating a sprite with a custom material there.

This is the translated SK shader (untested):
```
//*********************************************************
//
// Copyright (c) Microsoft. All rights reserved.
// This code is licensed under the MIT License (MIT).
// THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
// IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
// PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
//
//*********************************************************
#include <stereokit.hlsli>

//--name = quad_nv12
//--luminance       = white
//--chrominance     = white
Texture2D<float>  luminance   : register(t0);
Texture2D<float2> chrominance : register(t1);
SamplerState default_sampler  : register(s0);

// Derived from https://msdn.microsoft.com/en-us/library/windows/desktop/dd206750(v=vs.85).aspx
// Section: Converting 8-bit YUV to RGB888
static const float3x3 YUVtoRGBCoeffMatrix =
{
	1.164383f, 1.164383f, 1.164383f,
	0.000000f, -0.391762f, 2.017232f,
	1.596027f, -0.812968f, 0.000000f
};

float3 ConvertYUVtoRGB(float3 yuv)
{
	// Derived from https://msdn.microsoft.com/en-us/library/windows/desktop/dd206750(v=vs.85).aspx
	// Section: Converting 8-bit YUV to RGB888

	// These values are calculated from (16 / 255) and (128 / 255)
	yuv -= float3(0.062745f, 0.501960f, 0.501960f);
	yuv = mul(yuv, YUVtoRGBCoeffMatrix);

	return saturate(yuv);
}

struct vsIn
{
	float4 pos  : SV_Position;
	float3 norm : NORMAL0;
	float2 uv   : TEXCOORD0;
	float4 col  : COLOR0;
};
struct psIn
{
	float4 pos   : SV_POSITION;
	float2 uv    : TEXCOORD0;
	float4 color : COLOR0;
	uint view_id : SV_RenderTargetArrayIndex;
};

psIn vs(vsIn input, uint id : SV_InstanceID)
{
	psIn o;
	o.view_id = id % sk_view_count;
	id = id / sk_view_count;

	float3 world = mul(float4(input.pos.xyz, 1), sk_inst[id].world).xyz;
	o.pos = mul(float4(world, 1), sk_viewproj[o.view_id]);

	o.uv = input.uv;
	o.color = input.col * color * sk_inst[id].color;
	return o;
}
float4 ps(psIn input) : SV_TARGET
{
	float y = luminance.Sample(default_sampler, input.uv);
	float2 uv = chrominance.Sample(default_sampler, input.uv);

	return min16float4(ConvertYUVtoRGB(float3(y, uv)), 1.f);
}

```

**Comment by austinbhale** [comment]
Thanks nick! Closing since it seems to be outside the realm of sk_gpu for the time being
